FROM golang:1.14.2-alpine3.11

ENV	SERVICE_USER=myuser \
	SERVICE_UID=10001 \
	SERVICE_GROUP=mygroup \
	SERVICE_GID=10001

RUN	addgroup -g ${SERVICE_GID} ${SERVICE_GROUP} && \
	adduser -g "${SERVICE_NAME} user" -D -H -G ${SERVICE_GROUP} -s /sbin/nologin -u ${SERVICE_UID} ${SERVICE_USER} && \
	apk add --update libcap

ENV HATEAOS user
ENV USER_DATABASE mongodb
ENV MONGO_HOST user-db
ENV sourcesdir /go/src/github.com/microservices-demo/user/

WORKDIR /
EXPOSE 80

RUN mkdir /app

COPY . ${sourcesdir}
RUN cd ${sourcesdir} && go mod vendor

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o /app/main github.com/microservices-demo/user

RUN rm -rf /go

RUN	chmod -R +x /app && \
	chown -R ${SERVICE_USER}:${SERVICE_GROUP} /app && \ 
	setcap 'cap_net_bind_service=+ep' /app/main

USER ${SERVICE_USER}

CMD ["/app/main", "-port=80"]
